#代价地图的配置-通用配置文件
obstacle_range: 2.5 #机器人检测障碍物的最大范围
raytrace_range: 3.0 #机器人检测自由空间的最大范围
footprint: [[0.23,0.2],[-0.23,0.2],[-0.23,-0.2],[0.23,-0.2]] #机器人在地图占用面积，以机器人中心为原点
#模板footprint: [[x0, y0], [x1, y1], ... [xn, yn]]  
#footprint: [[0.18,0.15],[-0.18,0.15],[-0.18,-0.15],[0.18,-0.15]]
inflation_radius: 0.1  #障碍物的膨胀参数0.1-0.15，也就是机器人应该与障碍物保持的最小安全距离
max_obstacle_height: 0.4
min_obstacle_height: 0.05
#observation_sources参数列出代价地图需要关注的所有传感器信息，每一个传感器信息都将在后边列出详细信息。
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0.3}
