#代价地图的配置-全局配置文件
global_costmap:
   global_frame: /map  #参考系
   robot_base_frame: /base_footprint #表示代价地图可以参考的机器人本体的参考系
   update_frequency: 2.0 #全局地图更新频率
   publish_frequency: 0
   static_map: true  #决定代价地图是否需要根据map_server提供的地图信息进行初始化
   rolling_window: false
   resolution: 0.05
   transform_tolerance: 3.0
   map_type: costmap
