#代价地图的配置-本地配置文件
local_costmap:    
   global_frame: /map
   robot_base_frame: /base_footprint  #表示代价地图可以参考的机器人本体的参考系
   update_frequency: 2.0
   publish_frequency: 2.0
   static_map: false  #决定代价地图是否需要根据map_server提供的地图信息进行初始化
   rolling_window: true #用来设置在机器人移动过程中是否需要滚动窗口
   width: 3.0
   height: 3.0
   resolution: 0.05   #should same as map.yaml file
   transform_tolerance: 3.0
   map_type: costmap
   footprint_padding: 0.2
